version: '3'

services:
  proxy: 
    build:
      context: .
      dockerfile: nginxproxy.dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/testdocker.ddns.net/fullchain.pem:/etc/letsencrypt/live/testdocker.ddns.net/fullchain.pem
      - /etc/letsencrypt/live/testdocker.ddns.net/privkey.pem:/etc/letsencrypt/live/testdocker.ddns.net/privkey.pem

  nginxapp1:
    build:
      context: ./nginxapp1
      dockerfile: Dockerfile
    ports:
      - "8081:80"
  nginxapp2:
    build:
      context: ./nginxapp2
      dockerfile: Dockerfile
    ports:
     - "8082:80"

  httpapp1:
    image: httpd:2.4
    ports:
      - "8083:80"
    volumes:
      - ./apacheapp1/app:/usr/local/apache2/htdocs/

  httpapp2:
    image: httpd:2.4
    ports:
      - "8084:80"
    volumes:
      - ./apacheapp2/app:/usr/local/apache2/htdocs/


